jobs:  
- job: Build
  displayName: Build
  steps:

  - task: ArchiveFiles@2
    displayName: Archive files to .zip 
    inputs:
      rootFolderOrFile: '$(Build.Repository.LocalPath)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/_DataFactory.zip'
      replaceExistingArchive: true 

  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
